In [1]:
#importing libraries
import pandas as pd
import numpy as ny
import os

In [2]:
path = r'C:\Users\Bhati\OneDrive\Desktop\CF\Data Analytics Immersion\Achievement 4\11-Apr-2023 Instacart Basket Analysis'

In [3]:
# importing the new dataset orders_products_busiesttime
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_busiesttime.pkl'))

# Working on subset of first million rows

In [4]:
# creating subset of first million rows
df = df_ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 17)

In [6]:
df.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,price_range_loc,busiest day,busiest days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,Mid-range product,Regularly busy,Regularly busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,Mid-range product,Regularly busy,Regularly busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,Mid-range product,Busiest day,Busiest day,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,Mid-range product,Regularly busy,Least busy day,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,Mid-range product,Least busy,Least busy day,Average orders

In [7]:
df.groupby('product_name')

In [8]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.577493
2                17.320781
3                16.084944
4                17.530458
5                14.763075
6                16.658449
7                17.031590
8                15.076662
9                15.447580
10               18.681852
11               15.447411
12               14.327957
13               16.548642
14               16.960241
15               16.121948
16               17.803851
17               15.593633
18               19.674252
19               16.899756
20               16.255442
21               25.535479

In [9]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.577493
2     17.320781
3     16.084944
4     17.530458
5     14.763075
6     16.658449
7     17.031590
8     15.076662
9     15.447580
10    18.681852
11    15.447411
12    14.327957
13    16.548642
14    16.960241
15    16.121948
16    17.803851
17    15.593633
18    19.674252
19    16.899756
20    16.255442
21    25.535479
Name: order_number, dtype: float64

# Performing functions on entire dataframe

**aggregated mean of the “order_number” column grouped by “department_id” for a entire dataframe**

In [18]:
df_ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

it is observed that mean values of entire dataframe is slightly lower than that of subset of first million rows.

**Create a loyalty flag for existing customers using the transform() and loc() functions**

In [19]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(ny.max)

In [20]:
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,price_range_loc,busiest day,busiest days,busiest_period_of_day,max_order,loyalty_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,Mid-range product,Busiest day,Busiest day,Average orders,5,New customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,NaN,10,0,Mid-range product,Regularly busy,Least busy day,Most orders,3,New customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,Mid-range product,Least busy,Least busy day,Average orders,3,New customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,Mid-range product,Regularly busy,Busiest day,Average orders,26,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,Mid-range product,Regularly busy,Least busy day,Most orders,12,Regular customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,Mid-range product,Regularly busy,Busiest day,Average orders,20,Regular customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,Mid-range product,Regularly busy,Busiest day,Most orders,20,Regular customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,NaN,1,0,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,Mid-range product,Regularly busy,Least busy day,Most orders,43,Loyal customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,Mid-range product,Least busy,Least busy day,Most orders,43,Loyal customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,Mid-range product,Regularly busy,Least busy day,Most orders,13,Regular customer

In [21]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [22]:
df_ords_prods_merge.loc[(df_ords_prods_merge['max_order'] <= 40) & (df_ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [23]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [24]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [25]:
#Performing multiple aggregations ('min', 'max', 'mean', 'sum')
df_ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max', 'sum']})

                     prices
                       mean  min      max          sum
loyalty_flag
Loyal customer    10.386336  1.0  99999.0  106814042.2
New customer      13.294670  1.0  99999.0   83011787.2
Regular customer  12.495717  1.0  99999.0  198391693.2

1. 'Loyal customers' purchase on average cheaper products than 'New customers' and 'Regular customers'
2. Sum of 'Regular customer' is higher as they are more in number than the other two types of customers and also there is no huge difference in mean

**Create a spending flag for each user based on the average price across all their orders using the following criteria**

In [27]:
df_ords_prods_merge['avg_price'] = df_ords_prods_merge.groupby(['user_id'])['prices'].transform(ny.mean)

In [28]:
df_ords_prods_merge.loc[df_ords_prods_merge['avg_price'] >= 10, 'spending_flag'] = 'High spender'

In [29]:
df_ords_prods_merge.loc[df_ords_prods_merge['avg_price'] < 10, 'spending_flag'] = 'Low spender'

In [31]:
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,add_to_cart_order,reordered,price_range_loc,busiest day,busiest days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,Mid-range product,Busiest day,Busiest day,Average orders,5,New customer,7.930208,Low spender
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,Mid-range product,Regularly busy,Least busy day,Most orders,3,New customer,4.972414,Low spender
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,Mid-range product,Least busy,Least busy day,Average orders,3,New customer,4.972414,Low spender
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,7,0,Mid-range product,Regularly busy,Busiest day,Average orders,26,Regular customer,6.935398,Low spender
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,2,0,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576,Low spender
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,1,0,Mid-range product,Regularly busy,Least busy day,Most orders,12,Regular customer,6.680000,Low spender
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,1,0,Mid-range product,Regularly busy,Busiest day,Average orders,20,Regular customer,7.162500,Low spender
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,2,1,Mid-range product,Regularly busy,Busiest day,Most orders,20,Regular customer,7.162500,Low spender
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,1,0,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636,Low spender
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,1,0,Mid-range product,Regularly busy,Least busy day,Most orders,43,Loyal customer,5.081633,Low spender
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,3,1,Mid-range product,Least busy,Least busy day,Most orders,43,Loyal customer,5.081633,Low spender
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,4,1,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633,Low spender
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,8,0,Mid-range product,Regularly busy,Least busy day,Most orders,13,Regular customer,6.803797,Low spender

In [32]:
df_ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

**Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column**

In [33]:
df_ords_prods_merge['median_freq'] = df_ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(ny.median)

In [34]:
df_ords_prods_merge.loc[df_ords_prods_merge['median_freq'] > 20, 'order_freq_flag'] = 'Non-frequent customer'

In [35]:
df_ords_prods_merge.loc[(df_ords_prods_merge['median_freq'] > 10) & (df_ords_prods_merge['median_freq'] <= 20), 'order_freq_flag'] = 'Regular customer'

In [36]:
df_ords_prods_merge.loc[df_ords_prods_merge['median_freq'] <= 10, 'order_freq_flag'] = 'Frequent customer'

In [37]:
df_ords_prods_merge.head(15)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,price_range_loc,busiest day,busiest days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spending_flag,median_freq,order_freq_flag
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,Mid-range product,Busiest day,Busiest day,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,Mid-range product,Regularly busy,Least busy day,Most orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,Mid-range product,Least busy,Least busy day,Average orders,3,New customer,4.972414,Low spender,9.0,Frequent customer
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,...,Mid-range product,Regularly busy,Busiest day,Average orders,26,Regular customer,6.935398,Low spender,11.0,Regular customer
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,...,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576,Low spender,20.0,Regular customer
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,...,Mid-range product,Regularly busy,Least busy day,Most orders,12,Regular customer,6.680000,Low spender,6.0,Frequent customer
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,...,Mid-range product,Regularly busy,Busiest day,Average orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,...,Mid-range product,Regularly busy,Busiest day,Most orders,20,Regular customer,7.162500,Low spender,10.0,Frequent customer
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,...,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636,Low spender,20.0,Regular customer
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,...,Mid-range product,Regularly busy,Least busy day,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,...,Mid-range product,Least busy,Least busy day,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,...,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633,Low spender,7.0,Frequent customer
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,...,Mid-range product,Regularly busy,Least busy day,Most orders,13,Regular customer,6.803797,Low spender,7.0,Frequent customer

In [38]:
df_ords_prods_merge['order_freq_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: order_freq_flag, dtype: int64

In [39]:
df_ords_prods_merge.shape

(32404859, 23)

# Exporting the final to Prepared Data

In [40]:
df_ords_prods_merge.to_pickle(os.path.join(path,'02 Data','Prepared Data','orders_products_aggregated.pkl'))